[package]
name = "fastbm25"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastbm25"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
rayon = "1.8"
